config/routes.rb
Rails.application.routes.draw do
  get 'wiki_posts/example'
  resources :wiki_posts
  get 'welcome/index'
  get 'welcome/about'
  get '/about', to: redirect('/welcome/about')
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wiki_post.rb
class WikiPost < ApplicationRecord
    has_one_attached :image
    def meta
        "Created by " + self.author + " on " + I18n.l(self.created_at, format: :long) + " and last updated " + I18n.l(self.updated_at, format: :long)
    end   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @wiki_posts = WikiPost.all
  end
  def about
  end
end

app/controllers/wiki_posts_controller.rb
class WikiPostsController < ApplicationController
  before_action :set_wiki_post, only: %i[ show edit update destroy ]

  # GET /wiki_posts or /wiki_posts.json
  def index
    @wiki_posts = WikiPost.all
  end

  # GET /wiki_posts/1 or /wiki_posts/1.json
  def show
  end

  def example
  end

  # GET /wiki_posts/new
  def new
    @wiki_post = WikiPost.new
  end

  # GET /wiki_posts/1/edit
  def edit
  end

  # POST /wiki_posts or /wiki_posts.json
  def create
    @wiki_post = WikiPost.new(wiki_post_params)

    respond_to do |format|
      if @wiki_post.save
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully created." }
        format.json { render :show, status: :created, location: @wiki_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wiki_posts/1 or /wiki_posts/1.json
  def update
    respond_to do |format|
      if @wiki_post.update(wiki_post_params)
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "You updated wiki post "+"\""+@wiki_post.title+""}
        format.json { render :show, status: :ok, location: @wiki_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiki_posts/1 or /wiki_posts/1.json
  def destroy
    @wiki_post.destroy

    respond_to do |format|
      format.html { redirect_to wiki_posts_url, notice: "Wiki post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki_post
      @wiki_post = WikiPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wiki_post_params
      params.fetch(:wiki_post, {}).permit(:title, :description, :image, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_posts_helper.rb
module WikiPostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Wiki Information</h1>

app/views/welcome/index.html.erb
<h1>Wiki</h1>

<div>
  <% @posts.each do |post| %>
    <p>
      <h4><%= post.title %></h4>
      <%= link_to "View", wiki_post_path(post), class: "wikiLink" %>
    </p>
  <% end %>
</div>

<%= link_to "About", welcome_about_path %>
<%= link_to "New Post", new_wiki_post_path %>

app/views/wiki_posts/_form.html.erb
<%= form_with(model: wiki_post) do |form| %>
  <% if wiki_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wiki_post.errors.count, "error") %> prohibited this wiki_post from being saved:</h2>

      <ul>
        <% wiki_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :title, "Post Title" %>
  <%= form.text_field :title %>

  <%= form.label :image, "Post Image" %>
  <%= form.file_field :image %>

  <%= form.label :title, "Post Description" %>
  <%= form.text_field :description %>

  <%= form.label :title, "Your Name:" %>
  <%= form.text_field :author %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wiki_posts/_list.html.erb
<div class="posts">
  <% @wiki_posts.each do |post| %>
    <p>
      <h4><%= post.title %></h4>
      <%= link_to "View", wiki_post_path(post), class: "wikiLink" %>
      <%
=begin%>
 <%= image_tag post.image , class: 'thumbnail' %> 
<%
=end%>
    </p>
  <% end %>
</div>

app/views/wiki_posts/_meta.html.erb
<div class="meta">
    Created by <strong><%= @wiki_post.author %></strong> on
    <strong><%= @wiki_post.created_at %></strong> and last updated 
    <strong><%= @wiki_post.updated_at %></strong>
</div>

app/views/wiki_posts/edit.html.erb
<h1>Editing Wiki Post</h1>

<% render 'form', wiki_post: @wiki_post %>

<%= link_to 'Show', @wiki_post %> |
<%= link_to 'Back', wiki_posts_path %>

app/views/wiki_posts/example.html.erb
<h1 class="title">Wiki Page Title</h1>

<div class="container">
    <p class="description">Wiki Page Body</p>

    <div class="meta">
        <span class="author">Author</span> 
        <span class="creation">Creation Date</span> 
        <span class="update">Last Update Date</span>
    </div>
</div>

<div class="links">
    <%= link_to "Home", welcome_index_path %>
    <%= link_to "New Wiki Post", new_wiki_post_path %>
</div>

app/views/wiki_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wiki Posts</h1>

<%= link_to 'New Wiki Post', new_wiki_post_path %>

app/views/wiki_posts/new.html.erb
<h1>New Wiki Post</h1>

<%= render 'form', wiki_post: @wiki_post %>

<%= link_to 'Back', wiki_posts_path %>

app/views/wiki_posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
    <%= @wiki_post.title %>
</h1>
   

<%
=begin%>
 <%= image_tag(@wiki_post.image) %> 
<%
=end%>

<p>
    <%= @wiki_post.description %>
</p>

<%= render 'meta', wiki_post: @wiki_post %>


<div>
    <%= link_to 'Edit', edit_wiki_post_path(@wiki_post) %> |
    <%= link_to 'Delete', wiki_post_path(@wiki_post), method: :destroy %> |
    <%= link_to 'Back', wiki_posts_path %>
</div>